export const nikeProducts = [
  {
    id: 1,
    status: "Just In",
    title: "Nike Air Force 1 Mid '07",
    description:
      "The Nike Air Force 1 Mid '07 brings the iconic basketball shoe to new heights with a mid-top design. Its cushioned feel and timeless style make it perfect for on and off the court. Crafted with premium materials and a bold silhouette, it combines comfort and durability for everyday wear.",
    shortDescription:
      "Classic basketball shoe with a mid-top design. Features premium materials and a cushioned feel for comfort. Durable and stylish for everyday use.",
    color: "1 Colour",
    colors: ["White"],
    category: "Men's Shoes",
    inventory: 25,
    brandName: "Nike",
    tags: ["Basketball", "Casual", "Comfort"],
    sku: "NAF1M07",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 10795,
    discountedPrice: 9995,

    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-1.png",
  },
  {
    id: 2,
    status: "Just In",
    title: "Nike Court Vision Low Next Nature",
    description:
      "The Nike Court Vision Low Next Nature is a perfect blend of retro style and modern sustainability. Inspired by basketball aesthetics, these shoes are crafted with at least 20% recycled materials by weight. The low-profile design ensures versatility, making it an ideal choice for casual outings and sporty looks.",
    shortDescription:
      "Low-profile, retro basketball-inspired shoe. Made with at least 20% recycled materials. Stylish and sustainable for everyday wear.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 30,
    brandName: "Nike",
    tags: ["Basketball", "Sustainability", "Casual"],
    sku: "NCVLNN",
    returnPolicy: "30 days return policy",
    rating: 4.2,
    currentPrice: 4995,
    discountedPrice: 4500,

    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-2.png",
  },
  {
    id: 3,
    status: "Just In",
    title: "Nike Air Force 1 PLT.AF.ORM",
    description:
      "The Nike Air Force 1 PLT.AF.ORM redefines a classic silhouette with a modern twist. Designed for women, these shoes combine sleek aesthetics with unparalleled comfort. The platform sole adds height and makes a bold statement, while premium materials ensure durability for long-term use.",
    shortDescription:
      "Women's platform sneaker with a modern take on a classic. Premium materials and a bold sole for style and comfort.",
    color: "1 Colour",
    colors: ["Pink"],
    category: "Women's Shoes",
    inventory: 20,
    brandName: "Nike",
    tags: ["Platform", "Classic", "Style"],
    sku: "NAF1PAO",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 8695,
    discountedPrice: 8200,

    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-3.png",
  },
  {
    id: 4,
    status: "Just In",
    title: "Nike Air Force 1 React",
    description:
      "The Nike Air Force 1 React takes a revolutionary approach to a classic. Incorporating Nike React technology, these men's shoes deliver superior cushioning and responsiveness. With a futuristic design and signature Air Force 1 elements, this pair is built for those who love to stand out.",
    shortDescription:
      "Futuristic take on the classic Air Force 1. Features Nike React technology for extra comfort. Perfect for bold, standout looks.",
    color: "1 Colour",
    colors: ["Blue"],
    category: "Men's Shoes",
    inventory: 15,
    brandName: "Nike",
    tags: ["React Technology", "Comfort", "Bold"],
    sku: "NAF1R",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 13295,
    discountedPrice: 12500,

    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-4.png",
  },
  {
    id: 5,
    status: "Promo Exclusion",
    title: "Air Jordan 1 Elevate Low",
    description:
      "The Air Jordan 1 Elevate Low brings a fresh perspective to the iconic Jordan line. These women's shoes feature a low-cut design with platform soles, offering a chic, modern vibe. With premium craftsmanship and a nod to basketball heritage, they're perfect for making a statement.",
    shortDescription:
      "Low-cut women's shoes with platform soles. Combines basketball heritage with a modern vibe. Stylish and crafted for all-day wear.",
    color: "1 Colour",
    colors: ["Red"],
    category: "Women's Shoes",
    inventory: 18,
    brandName: "Jordan",
    tags: ["Basketball Heritage", "Platform", "Fashion"],
    sku: "AJ1EL",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 11895,
    discountedPrice: 11000,

    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-5.png",
  },
  {
    id: 6,
    status: "Just In",
    title: "Nike Standard Issue",
    description:
      "The Nike Standard Issue Women's Basketball Jersey combines performance and style for the court. With sweat-wicking fabric and a relaxed fit, it's perfect for intense games and casual outings. The design is inspired by classic basketball uniforms, offering both functionality and timeless appeal.",
    shortDescription:
      "Women's basketball jersey with sweat-wicking fabric. Relaxed fit for comfort during games or casual wear.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Apparel",
    inventory: 40,
    brandName: "Nike",
    tags: ["Basketball", "Apparel", "Comfort"],
    sku: "NSIWJ",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 2895,
    discountedPrice: 2500,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-6.png",
  },
  {
    id: 7,
    status: "Promo Exclusion",
    title: "Nike Dunk Low Retro SE",
    description:
      "The Nike Dunk Low Retro SE revives a classic basketball silhouette with modern updates. These men's shoes feature premium materials and bold color accents for a standout look. Comfortable for everyday wear, they're a must-have for sneaker enthusiasts and basketball fans alike.",
    shortDescription:
      "Classic basketball-inspired sneaker with bold accents. Premium materials ensure comfort and durability.",
    color: "1 Colour",
    colors: ["Blue"],
    category: "Men's Shoes",
    inventory: 22,
    brandName: "Nike",
    tags: ["Basketball", "Retro", "Sneaker"],
    sku: "NDLRSE",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 9695,
    discountedPrice: 8995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-7.png",
  },
  {
    id: 8,
    status: "Sustainable Materials",
    title: "Nike Dri-FIT UV Hyverse",
    description:
      "Stay cool and protected with the Nike Dri-FIT UV Hyverse Men's Short Sleeve Graphic Fitness Top. Made with sweat-wicking fabric and sustainable materials, it ensures optimal comfort during workouts. Its lightweight design and UV protection make it ideal for outdoor activities.",
    shortDescription:
      "Men's fitness top with sweat-wicking fabric. Lightweight, UV protection, and made with sustainable materials.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Apparel",
    inventory: 35,
    brandName: "Nike",
    tags: ["Sustainable", "Fitness", "UV Protection"],
    sku: "NDFUVH",
    returnPolicy: "30 days return policy",
    rating: 4.3,
    currentPrice: 2495,
    discountedPrice: 2295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-8.png",
  },
  {
    id: 9,
    status: "Just In",
    title: "Nike Court Vision Low",
    description:
      "The Nike Court Vision Low updates a classic basketball-inspired design with sleek, modern details. These men's shoes are crafted for style and versatility, featuring a low-profile silhouette and durable materials for everyday wear.",
    shortDescription:
      "Sleek and versatile basketball-inspired sneaker. Durable materials for everyday comfort and style.",
    color: "1 Colour",
    colors: ["White"],
    category: "Men's Shoes",
    inventory: 28,
    brandName: "Nike",
    tags: ["Basketball", "Versatile", "Casual"],
    sku: "NCVL",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 5695,
    discountedPrice: 5295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-9.png",
  },
  {
    id: 10,
    status: "Just In",
    title: "Nike Dri-FIT Ready",
    description:
      "The Nike Dri-FIT Ready Men's Short Sleeve Fitness Top is designed for peak performance. Featuring sweat-wicking fabric and a lightweight construction, it ensures you stay dry and comfortable during intense workouts. Available in three colors, it offers versatile style for any activity.",
    shortDescription:
      "Men's fitness top with sweat-wicking technology. Lightweight and available in three colors for versatile wear.",
    color: "3 Colours",
    colors: ["Gray", "Black", "Blue"],
    category: "Men's Apparel",
    inventory: 45,
    brandName: "Nike",
    tags: ["Fitness", "Lightweight", "Comfort"],
    sku: "NDFR",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 2495,
    discountedPrice: 2395,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-10.png",
  },
  {
    id: 11,
    status: "Just In",
    title: "Nike One Leak Protection: Period",
    description:
      "The Nike One Leak Protection: Period Women's Biker Shorts provide confidence and comfort during your period. Featuring leak protection technology and a mid-rise design, these 18cm shorts are crafted for both performance and everyday wear. With a focus on inclusivity, they redefine comfort for active women.",
    shortDescription:
      "Mid-rise biker shorts with leak protection. Designed for performance and everyday confidence.",
    color: "2 Colours",
    colors: ["Black", "Red"],
    category: "Women's Apparel",
    inventory: 20,
    brandName: "Nike",
    tags: ["Leak Protection", "Comfort", "Biker Shorts"],
    sku: "NOLPP",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 3395,
    discountedPrice: 3195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-11.png",
  },
  {
    id: 12,
    status: "Just In",
    title: "Nike Air Force 1 LV8 3",
    description:
      "The Nike Air Force 1 LV8 3 for older kids elevates the iconic silhouette with fresh details and premium materials. Designed for style and durability, it offers the comfort and support kids need for all-day adventures.",
    shortDescription:
      "Iconic kids' shoe with updated details. Durable and stylish for everyday wear.",
    color: "1 Colour",
    colors: ["White"],
    category: "Kids' Shoes",
    inventory: 25,
    brandName: "Nike",
    tags: ["Kids", "Durable", "Stylish"],
    sku: "NAF1LV83",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 7495,
    discountedPrice: 6995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-12.png",
  },

  {
    id: 13,
    status: "Just In",
    title: "Nike Blazer Low Platform",
    description:
      "The Nike Blazer Low Platform Women's Shoes offer a sleek, elevated take on a classic design. Featuring a low-profile silhouette with a stacked platform sole, they provide a stylish edge while maintaining all-day comfort. Perfect for casual and semi-formal occasions.",
    shortDescription:
      "Women's platform shoes with a classic low-profile design. Stylish, versatile, and comfortable for everyday wear.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Shoes",
    inventory: 30,
    brandName: "Nike",
    tags: ["Platform", "Stylish", "Casual"],
    sku: "NBLP",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 8195,
    discountedPrice: 7695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-13.png",
  },
  {
    id: 14,
    status: "Just In",
    title: "Nike Air Force 1 '07",
    description:
      "The timeless Nike Air Force 1 '07 Women's Shoe combines classic court style with modern updates. With its clean lines, durable materials, and two vibrant color options, this shoe is perfect for any occasion, from casual outings to streetwear looks.",
    shortDescription:
      "Classic women's shoe with modern updates. Durable and available in two color options.",
    color: "2 Colours",
    colors: ["White", "Pink"],
    category: "Women's Shoes",
    inventory: 25,
    brandName: "Nike",
    tags: ["Classic", "Durable", "Stylish"],
    sku: "NAF107",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 8195,
    discountedPrice: 7995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-14.png",
  },
  {
    id: 15,
    status: "Just In",
    title: "Nike Pro Dri-FIT",
    description:
      "Stay dry and focused during your workouts with the Nike Pro Dri-FIT Men's Tight-Fit Sleeveless Top. Made with lightweight, sweat-wicking fabric, this top ensures maximum comfort and mobility. Its tight fit provides excellent support for high-intensity training sessions.",
    shortDescription:
      "Men's sleeveless top with sweat-wicking fabric. Tight fit for enhanced mobility and support.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Apparel",
    inventory: 50,
    brandName: "Nike",
    tags: ["Performance", "Sweat-Wicking", "Comfort"],
    sku: "NPDF",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 1495,
    discountedPrice: 1295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-15.png",
  },
  {
    id: 16,
    status: "Just In",
    title: "Nike Dunk Low Retro",
    description:
      "The Nike Dunk Low Retro Men's Shoes bring a fresh look to a classic basketball-inspired silhouette. With premium materials and a bold design, these shoes are perfect for both on-court performance and everyday streetwear.",
    shortDescription:
      "Classic basketball-inspired shoes with bold design. Perfect for performance and streetwear.",
    color: "1 Colour",
    colors: ["Blue"],
    category: "Men's Shoes",
    inventory: 20,
    brandName: "Nike",
    tags: ["Retro", "Basketball", "Streetwear"],
    sku: "NDLR",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 8695,
    discountedPrice: 8495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-16.png",
  },
  {
    id: 17,
    status: "Just In",
    title: "Nike Air Max SC",
    description:
      "The Nike Air Max SC Women's Shoes offer a perfect blend of style and comfort. Featuring two color options and the iconic Air Max cushioning, these shoes provide a versatile look and all-day comfort for any activity.",
    shortDescription:
      "Stylish women's shoes with Air Max cushioning. Versatile design with two color options.",
    color: "2 Colours",
    colors: ["White", "Black"],
    category: "Women's Shoes",
    inventory: 18,
    brandName: "Nike",
    tags: ["Air Max", "Comfort", "Versatile"],
    sku: "NAMSC",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 5995,
    discountedPrice: 5695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-17.png",
  },
  {
    id: 18,
    status: "Just In",
    title: "Nike Dri-FIT UV Miler",
    description:
      "Run with confidence in the Nike Dri-FIT UV Miler Men's Short Sleeve Running Top. Designed with sweat-wicking fabric and UV protection, it keeps you dry and protected during outdoor runs. Lightweight and breathable, it's the ultimate running companion.",
    shortDescription:
      "Men's running top with sweat-wicking fabric. UV protection and lightweight design for outdoor activities.",
    color: "1 Colour",
    colors: ["Blue"],
    category: "Men's Apparel",
    inventory: 40,
    brandName: "Nike",
    tags: ["Running", "UV Protection", "Lightweight"],
    sku: "NDFUV",
    returnPolicy: "30 days return policy",
    rating: 4.3,
    currentPrice: 1695,
    discountedPrice: 1495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-18.png",
  },
  {
    id: 19,
    status: "Just In",
    title: "Nike Air Max SYSTM",
    description:
      "The Nike Air Max SYSTM Older Kids' Shoes offer comfort and style for growing feet. Featuring the iconic Air Max cushioning and a durable design, these shoes are perfect for all-day wear and active lifestyles.",
    shortDescription:
      "Kids' shoes with Air Max cushioning. Durable and stylish for active lifestyles.",
    color: "1 Colour",
    colors: ["Gray"],
    category: "Kids' Shoes",
    inventory: 25,
    brandName: "Nike",
    tags: ["Air Max", "Kids", "Durable"],
    sku: "NAMSYS",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 6495,
    discountedPrice: 6195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-19.png",
  },
  {
    id: 20,
    status: "Just In",
    title: "Nike Alate All U",
    description:
      "The Nike Alate All U Women's Sports Bra combines light support with a lightly lined design for ultimate comfort. Featuring a unique U-neck and printed pattern, it's perfect for low-impact activities or casual wear.",
    shortDescription:
      "Women's sports bra with light support and U-neck design. Stylish and comfortable for low-impact activities.",
    color: "1 Colour",
    colors: ["Pink"],
    category: "Women's Apparel",
    inventory: 35,
    brandName: "Nike",
    tags: ["Sports Bra", "Light Support", "Stylish"],
    sku: "NAAU",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 2195,
    discountedPrice: 1995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-20.png",
  },

  {
    id: 21,
    status: "Just In",
    title: "Nike Court Legacy Lift",
    description:
      "The Nike Court Legacy Lift Women's Shoes combine a classic silhouette with elevated details. Featuring two color options and a durable construction, these shoes offer a versatile and stylish addition to your wardrobe, ideal for casual outings and athletic wear.",
    shortDescription:
      "Women's shoes with a classic design. Durable and versatile for everyday use in two color options.",
    color: "2 Colours",
    colors: ["White", "Black"],
    category: "Women's Shoes",
    inventory: 22,
    brandName: "Nike",
    tags: ["Classic", "Casual", "Versatile"],
    sku: "NCLL",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 7495,
    discountedPrice: 7295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-21.png",
  },
  {
    id: 22,
    status: "Just In",
    title: "Nike Swoosh",
    description:
      "The Nike Swoosh Women's Medium Support Padded Sports Bra Tank offers a stylish and supportive fit. Designed for medium-impact activities, this sports bra features a unique tank style, with padded support and a breathable fabric that keeps you comfortable during workouts.",
    shortDescription:
      "Medium support sports bra tank with breathable fabric. Perfect for medium-impact activities and stylish wear.",
    color: "2 Colours",
    colors: ["Black", "Pink"],
    category: "Women's Apparel",
    inventory: 40,
    brandName: "Nike",
    tags: ["Sports Bra", "Support", "Breathable"],
    sku: "NSBR",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 3095,
    discountedPrice: 2895,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-22.png",
  },
  {
    id: 23,
    status: "Just In",
    title: "Nike SB Zoom Janoski OG+",
    description:
      "The Nike SB Zoom Janoski OG+ Shoes offer a modern take on the classic skateboarding design. With Zoom Air cushioning and a durable rubber sole, these shoes provide superior comfort and grip, ideal for both skateboarding and casual wear.",
    shortDescription:
      "Skateboarding shoes with Zoom Air cushioning. Durable and comfortable for both performance and casual use.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 18,
    brandName: "Nike SB",
    tags: ["Skateboarding", "Zoom Air", "Comfort"],
    sku: "NSBJJ",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 8595,
    discountedPrice: 8395,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-23.png",
  },
  {
    id: 24,
    status: "Just In",
    title: "Nike Dri-FIT Run Division Rise 365",
    description:
      "The Nike Dri-FIT Run Division Rise 365 Men's Running Tank is designed to keep you cool and comfortable during your run. With breathable, sweat-wicking fabric and reflective details for visibility, this tank is the ultimate performance wear for your outdoor training.",
    shortDescription:
      "Men's running tank with sweat-wicking fabric and reflective details. Perfect for outdoor training and running.",
    color: "2 Colours",
    colors: ["Blue", "Black"],
    category: "Men's Apparel",
    inventory: 50,
    brandName: "Nike",
    tags: ["Running", "Breathable", "Reflective"],
    sku: "NDFRD",
    returnPolicy: "30 days return policy",
    rating: 4.3,
    currentPrice: 3495,
    discountedPrice: 3195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-24.png",
  },
  {
    id: 25,
    status: "Just In",
    title: "Nike Dri-FIT Challenger",
    description:
      "The Nike Dri-FIT Challenger Men's 18cm (approx.) 2-in-1 Versatile Shorts are perfect for any athletic activity. Featuring sweat-wicking fabric and a built-in liner for extra support, these shorts provide ultimate comfort and mobility during workouts or runs.",
    shortDescription:
      "Men's 2-in-1 versatile shorts with sweat-wicking fabric and built-in liner for support. Great for athletic activities.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Apparel",
    inventory: 30,
    brandName: "Nike",
    tags: ["Performance", "Support", "Versatile"],
    sku: "NDFCS",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 2495,
    discountedPrice: 2295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-25.png",
  },
  {
    id: 26,
    status: "Just In",
    title: "Jordan Series ES",
    description:
      "The Jordan Series ES Men's Shoes bring iconic design and modern comfort together. Featuring two stylish color options and durable construction, these shoes offer all-day comfort and a timeless look, perfect for any occasion, whether casual or athletic.",
    shortDescription:
      "Men's shoes with iconic design and modern comfort. Available in two color options, ideal for any occasion.",
    color: "2 Colours",
    colors: ["Red", "Black"],
    category: "Men's Shoes",
    inventory: 40,
    brandName: "Jordan",
    tags: ["Comfort", "Durable", "Stylish"],
    sku: "JSES",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 7495,
    discountedPrice: 7195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-26.png",
  },

  {
    id: 27,
    status: "Just In",
    title: "Nike Outdoor Play",
    description:
      "The Nike Outdoor Play Older Kids' Oversized Woven Jacket is perfect for young adventurers. Made from durable fabric, this jacket offers warmth and style, designed to keep kids comfortable during outdoor activities in various weather conditions.",
    shortDescription:
      "Older kids' oversized woven jacket for outdoor activities. Durable and warm, perfect for all weather.",
    color: "1 Colour",
    colors: ["Green"],
    category: "Kids' Apparel",
    inventory: 25,
    brandName: "Nike",
    tags: ["Outdoor", "Adventure", "Comfort"],
    sku: "NOPJ",
    returnPolicy: "30 days return policy",
    rating: 4.3,
    currentPrice: 3895,
    discountedPrice: 3695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-27.png",
  },
  {
    id: 28,
    status: "Just In",
    title: "Nike Sportswear Trend",
    description:
      "The Nike Sportswear Trend Older Kids' (Girls') High Waisted Woven Shorts are designed for comfort and style. These shorts feature a high-waisted fit and a breathable fabric, making them perfect for warm weather and outdoor play.",
    shortDescription:
      "High-waisted woven shorts for older kids, ideal for warm weather. Comfortable and breathable fabric.",
    color: "2 Colours",
    colors: ["Pink", "Black"],
    category: "Kids' Apparel",
    inventory: 30,
    brandName: "Nike",
    tags: ["Summer Wear", "Comfort", "Breathable"],
    sku: "NSTW",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 2495,
    discountedPrice: 2295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-28.png",
  },
  {
    id: 29,
    status: "Just In",
    title: "Nike Blazer Low '77 Jumbo",
    description:
      "The Nike Blazer Low '77 Jumbo Women's Shoes offer a stylish and retro design with jumbo Swoosh detailing. These shoes are crafted for comfort and durability, making them a versatile option for everyday wear.",
    shortDescription:
      "Women's shoes with a retro design and jumbo Swoosh. Comfortable and stylish for everyday wear.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Shoes",
    inventory: 40,
    brandName: "Nike",
    tags: ["Retro", "Stylish", "Comfortable"],
    sku: "NBLJ",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 8595,
    discountedPrice: 8395,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-29.png",
  },
  {
    id: 30,
    status: "Just In",
    title: "Nike SB Force 58",
    description:
      "The Nike SB Force 58 Skate Shoe combines durability with style. Featuring a sleek design and a cushioned sole, these shoes offer excellent grip and comfort, ideal for both skating and casual wear.",
    shortDescription:
      "Skate shoes with cushioned soles for comfort and superior grip. Ideal for skating and casual wear.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 18,
    brandName: "Nike SB",
    tags: ["Skateboarding", "Durable", "Comfort"],
    sku: "NSBF58",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 5995,
    discountedPrice: 5795,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-30.png",
  },
  {
    id: 31,
    status: "Just In",
    title: "Nike Dri-FIT Run Division Challenger",
    description:
      "The Nike Dri-FIT Run Division Challenger Men's 13cm (approx.) Brief-Lined Running Shorts are made with lightweight, breathable fabric for a cool, dry feel during your runs. These shorts feature a built-in brief for extra support and comfort.",
    shortDescription:
      "Running shorts with brief lining for support. Lightweight and breathable fabric for a dry feel.",
    color: "2 Colours",
    colors: ["Grey", "Black"],
    category: "Men's Apparel",
    inventory: 35,
    brandName: "Nike",
    tags: ["Running", "Breathable", "Support"],
    sku: "NDFRC",
    returnPolicy: "30 days return policy",
    rating: 4.3,
    currentPrice: 2495,
    discountedPrice: 2395,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-31.png",
  },
  {
    id: 32,
    status: "Just In",
    title: "Nike Legend Essential 3 Next Nature",
    description:
      "The Nike Legend Essential 3 Next Nature Men's Training Shoes are designed for maximum comfort and durability. These shoes are crafted with sustainable materials, ensuring both high performance and environmental responsibility.",
    shortDescription:
      "Training shoes with sustainable materials. Durable and comfortable for high-performance training.",
    color: "2 Colours",
    colors: ["Blue", "Black"],
    category: "Men's Shoes",
    inventory: 28,
    brandName: "Nike",
    tags: ["Sustainable", "Training", "Comfort"],
    sku: "NLE3N",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 4995,
    discountedPrice: 4695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-32.png",
  },
  {
    id: 33,
    status: "Just In",
    title: "Nike Air Max SYSTM",
    description:
      "The Nike Air Max SYSTM Women's Shoes offer all-day comfort with a sleek design and responsive cushioning. These shoes provide a lightweight feel and superior support, making them perfect for everyday use and athletic wear.",
    shortDescription:
      "Women's shoes with responsive cushioning for comfort. Sleek design, ideal for both casual and athletic wear.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Shoes",
    inventory: 22,
    brandName: "Nike",
    tags: ["Comfort", "Cushioning", "Support"],
    sku: "NAS",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 8595,
    discountedPrice: 8295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-33.png",
  },
  {
    id: 34,
    status: "Just In",
    title: "Nike Dri-FIT Totality",
    description:
      "The Nike Dri-FIT Totality Men's 23cm (approx.) Unlined Shorts are perfect for intense workouts or casual wear. Designed with sweat-wicking fabric, these shorts keep you cool and dry during exercise while offering comfort and flexibility.",
    shortDescription:
      "Unlined shorts with sweat-wicking fabric for comfort. Perfect for workouts and casual wear.",
    color: "2 Colours",
    colors: ["Red", "Black"],
    category: "Men's Apparel",
    inventory: 40,
    brandName: "Nike",
    tags: ["Performance", "Breathable", "Flexible"],
    sku: "NDFT",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 1795,
    discountedPrice: 1695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-34.png",
  },
  {
    id: 35,
    status: "Just In",
    title: "Serena Williams Design Crew",
    description:
      "The Serena Williams Design Crew Women's Full Zip Top combines performance with style. This top is made with high-quality fabric for comfort and warmth, perfect for layering or casual wear.",
    shortDescription:
      "Women's full zip top with performance fabric. Comfortable and stylish for layering or casual wear.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Apparel",
    inventory: 33,
    brandName: "Serena Williams Design Crew",
    tags: ["Performance", "Warmth", "Style"],
    sku: "SWDCFT",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 5495,
    discountedPrice: 5195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-35.png",
  },
  {
    id: 36,
    status: "Just In",
    title: "Jordan Why Not .6 PF",
    description:
      "The Jordan Why Not .6 PF Men's Shoes are designed for high-performance athletes. Featuring responsive cushioning, durable construction, and a sleek design, these shoes are built to withstand the toughest training sessions and provide exceptional support.",
    shortDescription:
      "Men's shoes with responsive cushioning for athletes. Durable construction for tough training sessions.",
    color: "2 Colours",
    colors: ["Black", "White"],
    category: "Men's Shoes",
    inventory: 18,
    brandName: "Jordan",
    tags: ["Performance", "Athletic", "Cushioning"],
    sku: "JWNSPF",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 13995,
    discountedPrice: 13495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-36.png",
  },

  {
    id: 37,
    status: "Promo Exclusion",
    title: "Air Jordan 1 Low",
    description:
      "The Air Jordan 1 Low Women's Shoes are a sleek and stylish option for everyday wear. These shoes combine the iconic Jordan silhouette with a low-top design for a modern and versatile look.",
    shortDescription:
      "Women's shoes with iconic Jordan silhouette and low-top design. Stylish and versatile for daily wear.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Shoes",
    inventory: 20,
    brandName: "Jordan",
    tags: ["Stylish", "Iconic", "Comfort"],
    sku: "AJ1L",
    returnPolicy:
      "No promotional offers applicable. Standard return policy of 30 days.",
    rating: 4.5,
    currentPrice: 8295,
    discountedPrice: 7995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-37.png",
  },
  {
    id: 38,
    status: "Just In",
    title: "Nike Dri-FIT ADV TechKnit Ultra",
    description:
      "The Nike Dri-FIT ADV TechKnit Ultra Men's Short Sleeve Running Top is designed to keep you cool and comfortable during intense workouts. With advanced fabric technology, it offers breathability and moisture-wicking capabilities for enhanced performance.",
    shortDescription:
      "Short sleeve running top with advanced Dri-FIT technology. Breathable and moisture-wicking for performance.",
    color: "1 Colour",
    colors: ["Grey"],
    category: "Men's Apparel",
    inventory: 25,
    brandName: "Nike",
    tags: ["Running", "Performance", "Breathable"],
    sku: "NDFTUA",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 3895,
    discountedPrice: 3695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-38.png",
  },
  {
    id: 39,
    status: "Just In",
    title: "Nike Dri-FIT Form",
    description:
      "The Nike Dri-FIT Form Men's 18cm (approx.) Unlined Versatile Shorts are perfect for workouts, sports, and casual wear. Made with sweat-wicking fabric, they offer comfort and flexibility to keep you moving.",
    shortDescription:
      "Unlined shorts with sweat-wicking fabric for comfort and versatility. Ideal for workouts and casual wear.",
    color: "2 Colours",
    colors: ["Black", "Red"],
    category: "Men's Apparel",
    inventory: 30,
    brandName: "Nike",
    tags: ["Sweat-Wicking", "Versatile", "Comfort"],
    sku: "NDF",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 2395,
    discountedPrice: 2195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-39.png",
  },
  {
    id: 40,
    status: "Promo Exclusion",
    title: "Air Jordan 1 Mid",
    description:
      "The Air Jordan 1 Mid Women's Shoes feature a classic mid-top design with premium materials for a stylish and comfortable fit. These shoes offer timeless style with excellent support.",
    shortDescription:
      "Mid-top women's shoes with premium materials. Classic style and support for everyday wear.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Shoes",
    inventory: 18,
    brandName: "Jordan",
    tags: ["Premium", "Timeless", "Support"],
    sku: "AJ1M",
    returnPolicy:
      "No promotional offers applicable. Standard return policy of 30 days.",
    rating: 4.8,
    currentPrice: 11495,
    discountedPrice: 10995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-40.png",
  },
  {
    id: 41,
    status: "Just In",
    title: "Nike Dri-FIT ADV Run Division",
    description:
      "The Nike Dri-FIT ADV Run Division Women's Long-Sleeve Running Top offers enhanced moisture-wicking performance with a lightweight design. This top is perfect for long-distance runs or casual wear.",
    shortDescription:
      "Long-sleeve running top with moisture-wicking Dri-FIT technology. Lightweight and comfortable for runs.",
    color: "1 Colour",
    colors: ["Blue"],
    category: "Women's Apparel",
    inventory: 28,
    brandName: "Nike",
    tags: ["Running", "Breathable", "Comfort"],
    sku: "NDFARD",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 5295,
    discountedPrice: 4995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-41.png",
  },
  {
    id: 42,
    status: "Just In",
    title: "Nike Yoga",
    description:
      "The Nike Yoga Women's High Waisted 7/8 Leggings are designed for flexibility and comfort during yoga sessions. The soft fabric and high-waisted design ensure a snug fit that moves with your body.",
    shortDescription:
      "High-waisted leggings designed for yoga. Flexible and comfortable fabric for a snug fit.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Apparel",
    inventory: 30,
    brandName: "Nike",
    tags: ["Yoga", "Flexible", "Comfort"],
    sku: "NYOGA",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 3795,
    discountedPrice: 3595,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-42.png",
  },
  {
    id: 43,
    status: "Just In",
    title: "Nike Dri-FIT Totality",
    description:
      "The Nike Dri-FIT Totality Men's 18cm (approx.) Unlined Shorts are crafted from sweat-wicking fabric to keep you dry and comfortable during workouts. These versatile shorts offer flexibility and freedom of movement.",
    shortDescription:
      "Unlined shorts with sweat-wicking fabric for flexibility and comfort. Perfect for workouts.",
    color: "3 Colours",
    colors: ["Black", "Red", "Blue"],
    category: "Men's Apparel",
    inventory: 40,
    brandName: "Nike",
    tags: ["Sweat-Wicking", "Versatile", "Comfort"],
    sku: "NDFT3",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 1795,
    discountedPrice: 1695,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-43.png",
  },
  {
    id: 44,
    status: "Just In",
    title: "Nike Dri-FIT ADV Tour",
    description:
      "The Nike Dri-FIT ADV Tour Women's Short Sleeve Golf Polo offers comfort and style for your golf game. Made with moisture-wicking fabric, this polo ensures you stay dry and comfortable through your swing.",
    shortDescription:
      "Short sleeve golf polo with moisture-wicking Dri-FIT technology. Comfortable and stylish for golf.",
    color: "2 Colours",
    colors: ["White", "Pink"],
    category: "Women's Apparel",
    inventory: 22,
    brandName: "Nike",
    tags: ["Golf", "Moisture-Wicking", "Comfort"],
    sku: "NDFT",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 3695,
    discountedPrice: 3495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-44.png",
  },

  {
    id: 45,
    status: "Just In",
    title: "Nike Tanjun",
    description:
      "The Nike Tanjun Women's Shoes combine a lightweight design with comfort, making them perfect for everyday wear. With versatile styling and easy slip-on access, they are ideal for both active and casual outings.",
    shortDescription:
      "Lightweight and comfortable shoes for everyday wear. Easy slip-on design.",
    color: "2 Colours",
    colors: ["Black", "White"],
    category: "Women's Shoes",
    inventory: 15,
    brandName: "Nike",
    tags: ["Comfortable", "Casual", "Lightweight"],
    sku: "NTW",
    returnPolicy: "30 days return policy",
    rating: 4.4,
    currentPrice: 4995,
    discountedPrice: 4795,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-45.png",
  },
  {
    id: 46,
    status: "Sustainable Materials",
    title: "Nike Go",
    description:
      "The Nike Go Women's Firm Support High Waisted Leggings with Pockets offer a supportive and comfortable fit, ideal for both workouts and casual wear. Made with sustainable materials, these leggings also feature convenient pockets.",
    shortDescription:
      "High-waisted leggings made from sustainable materials with pockets for convenience and comfort.",
    color: "1 Colour",
    colors: ["Dark Grey"],
    category: "Women's Apparel",
    inventory: 20,
    brandName: "Nike",
    tags: ["Sustainable", "Supportive", "Comfortable"],
    sku: "NGH",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 5795,
    discountedPrice: 5595,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-46.png",
  },
  {
    id: 47,
    status: "Just In",
    title: "NikeCourt Victory",
    description:
      "The NikeCourt Victory Women's Tennis Tank is designed to provide flexibility and comfort during your tennis matches. With moisture-wicking technology, it helps keep you dry and focused on the game.",
    shortDescription:
      "Tennis tank top with moisture-wicking technology for comfort and flexibility during matches.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Apparel",
    inventory: 18,
    brandName: "Nike",
    tags: ["Tennis", "Moisture-Wicking", "Comfort"],
    sku: "NCV",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 1995,
    discountedPrice: 1795,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-47.png",
  },
  {
    id: 48,
    status: "Just In",
    title: "Nike Alpha",
    description:
      "The Nike Alpha Women's High Support Padded Sports Bra provides excellent support for high-impact activities. With a comfortable fit and padded design, this sports bra ensures maximum comfort and security during workouts.",
    shortDescription:
      "High-support padded sports bra designed for high-impact activities. Comfortable fit for workouts.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Apparel",
    inventory: 22,
    brandName: "Nike",
    tags: ["Supportive", "Comfortable", "High-Impact"],
    sku: "NAHSB",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 3695,
    discountedPrice: 3495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-48.png",
  },
  {
    id: 49,
    status: "Promo Exclusion",
    title: "Air Jordan 1 Mid SE",
    description:
      "The Air Jordan 1 Mid SE Men's Shoes feature premium materials and a stylish mid-top design, offering both comfort and an iconic look. These shoes are perfect for daily wear and are excluded from promotions.",
    shortDescription:
      "Premium mid-top design shoes with iconic Jordan style. Excluded from promotions.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 12,
    brandName: "Jordan",
    tags: ["Premium", "Iconic", "Comfort"],
    sku: "AJ1MSE",
    returnPolicy:
      "No promotional offers applicable. Standard return policy of 30 days.",
    rating: 4.8,
    currentPrice: 12295,
    discountedPrice: 11995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-49.png",
  },
  {
    id: 50,
    status: "Just In",
    title: "Nike Air Max 270 GO",
    description:
      "The Nike Air Max 270 GO Baby/Toddler Easy On/Off Shoes offer comfort and convenience with a design that makes them easy to put on and take off. These shoes are perfect for your little ones as they grow and explore.",
    shortDescription:
      "Easy on/off shoes for babies and toddlers with comfort and convenience.",
    color: "1 Colour",
    colors: ["Blue"],
    category: "Baby/Toddler Shoes",
    inventory: 25,
    brandName: "Nike",
    tags: ["Comfortable", "Easy-On", "Convenient"],
    sku: "NA270GO",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 6995,
    discountedPrice: 6795,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-50.png",
  },
  {
    id: 51,
    status: "Just In",
    title: "Nike Invincible 3 By You",
    description:
      "The Nike Invincible 3 By You Custom Men's Road Running Shoes offer personalized comfort and support for your running needs. With a custom fit and advanced cushioning, these shoes are designed to protect your feet during long runs.",
    shortDescription:
      "Customizable men's road running shoes with advanced cushioning and personalized fit.",
    color: "6 Colours",
    colors: ["Blue", "Red", "Green", "Black", "White", "Grey"],
    category: "Men's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Customizable", "Running", "Cushioning"],
    sku: "NI3BY",
    returnPolicy: "30 days return policy",
    rating: 4.9,
    currentPrice: 19295,
    discountedPrice: 17995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-51.png",
  },
  {
    id: 52,
    status: "Sustainable Materials",
    title: "Nike Air Max TW SE",
    description:
      "The Nike Air Max TW SE Men's Shoes are made with sustainable materials while offering exceptional comfort and style. These shoes are perfect for both casual wear and athletic activities.",
    shortDescription:
      "Men's shoes made with sustainable materials. Comfortable and stylish for various activities.",
    color: "1 Colour",
    colors: ["Grey"],
    category: "Men's Shoes",
    inventory: 14,
    brandName: "Nike",
    tags: ["Sustainable", "Comfortable", "Stylish"],
    sku: "NATWSE",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 15995,
    discountedPrice: 14995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-52.png",
  },
  {
    id: 53,
    status: "Just In",
    title: "Nike Invincible 3 By You",
    description:
      "The Nike Invincible 3 By You Custom Women's Road Running Shoes combine personalized fit with cutting-edge cushioning technology to provide maximum support and comfort on long runs.",
    shortDescription:
      "Customizable women's road running shoes with advanced cushioning and personalized fit.",
    color: "6 Colours",
    colors: ["Pink", "Purple", "White", "Black", "Grey", "Blue"],
    category: "Women's Shoes",
    inventory: 12,
    brandName: "Nike",
    tags: ["Customizable", "Running", "Cushioning"],
    sku: "NI3BYW",
    returnPolicy: "30 days return policy",
    rating: 4.9,
    currentPrice: 19295,
    discountedPrice: 17995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-53.png",
  },
  {
    id: 54,
    status: "Just In",
    title: "Nike Air Max 90 Futura By You",
    description:
      "The Nike Air Max 90 Futura By You Women's Shoes offer a customizable design and advanced cushioning, providing superior comfort and support for all-day wear. These shoes are perfect for those who want a personalized touch.",
    shortDescription:
      "Customizable women's shoes with advanced cushioning for comfort and support.",
    color: "6 Colours",
    colors: ["Blue", "Red", "Black", "White", "Pink", "Purple"],
    category: "Women's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Customizable", "Comfort", "Support"],
    sku: "NAM90F",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 17295,
    discountedPrice: 15995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-54.png",
  },

  {
    id: 55,
    status: "Just In",
    title: "Nike React Infinity 3 By You",
    description:
      "The Nike React Infinity 3 By You Custom Men's Road Running Shoes are designed to provide a custom fit with superior cushioning and support. Perfect for long-distance runners, these shoes offer comfort and style.",
    shortDescription:
      "Customizable men's road running shoes with advanced cushioning and support for long-distance runs.",
    color: "5 Colours",
    colors: ["Black", "Red", "Blue", "Green", "Yellow"],
    category: "Men's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Customizable", "Running", "Cushioning"],
    sku: "NRIBY",
    returnPolicy: "30 days return policy",
    rating: 4.9,
    currentPrice: 16995,
    discountedPrice: 15995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-55.png",
  },
  {
    id: 56,
    status: "Just In",
    title: "Nike Air Max 90 SE",
    description:
      "The Nike Air Max 90 SE Men's Shoes offer premium cushioning with a stylish design. These shoes are perfect for casual wear and light athletic activities, providing comfort throughout the day.",
    shortDescription:
      "Premium cushioning men's shoes for casual and light athletic wear.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 15,
    brandName: "Nike",
    tags: ["Comfortable", "Stylish"],
    sku: "NAM90SE",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 12795,
    discountedPrice: 11995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-56.png",
  },
  {
    id: 57,
    status: "Just In",
    title: "Nike Blazer Mid '77 Unlocked By You",
    description:
      "The Nike Blazer Mid '77 Unlocked By You Custom Men's Shoes offer personalized style and comfort. These shoes are made for those who appreciate classic design with a modern twist and superior cushioning.",
    shortDescription:
      "Customizable men's shoes with classic design and modern cushioning.",
    color: "9 Colours",
    colors: [
      "Black",
      "White",
      "Blue",
      "Red",
      "Green",
      "Purple",
      "Yellow",
      "Grey",
      "Brown",
    ],
    category: "Men's Shoes",
    inventory: 8,
    brandName: "Nike",
    tags: ["Customizable", "Cushioning", "Classic"],
    sku: "NBM77BY",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 13295,
    discountedPrice: 12995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-57.png",
  },
  {
    id: 58,
    status: "Just In",
    title: "Nike React Infinity 3 By You",
    description:
      "The Nike React Infinity 3 By You Custom Men's Road Running Shoes combine advanced cushioning and a custom fit for optimal performance during long-distance runs. Tailor them to your style for maximum comfort.",
    shortDescription:
      "Custom men's running shoes with personalized fit and advanced cushioning for long runs.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 12,
    brandName: "Nike",
    tags: ["Customizable", "Running", "Comfort"],
    sku: "NRIBY3",
    returnPolicy: "30 days return policy",
    rating: 4.9,
    currentPrice: 16995,
    discountedPrice: 15995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-58.png",
  },
  {
    id: 59,
    status: "Just In",
    title: "Nike Blazer Mid '77 Unlocked By You",
    description:
      "The Nike Blazer Mid '77 Unlocked By You Custom Women's Shoes offer a blend of timeless style and modern comfort. Customize your look with a variety of colors while enjoying a supportive fit.",
    shortDescription:
      "Customizable women's shoes with a timeless design and modern support.",
    color: "8 Colours",
    colors: [
      "Pink",
      "Blue",
      "Black",
      "White",
      "Red",
      "Purple",
      "Grey",
      "Green",
    ],
    category: "Women's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Customizable", "Comfortable", "Classic"],
    sku: "NBM77WBY",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 13295,
    discountedPrice: 12995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-59.png",
  },
  {
    id: 60,
    status: "Just In",
    title: "Nike Pegasus Trail 4 GORE-TEX",
    description:
      "The Nike Pegasus Trail 4 GORE-TEX Men's Waterproof Trail-Running Shoes are designed to keep your feet dry and comfortable in wet conditions. Ideal for trail running in all weather conditions, these shoes provide stability and cushioning.",
    shortDescription:
      "Waterproof trail-running shoes designed for wet conditions with stability and cushioning.",
    color: "1 Colour",
    colors: ["Grey"],
    category: "Men's Shoes",
    inventory: 7,
    brandName: "Nike",
    tags: ["Waterproof", "Trail Running", "Comfort"],
    sku: "NPTGORE",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 14995,
    discountedPrice: 13995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-60.png",
  },
  {
    id: 61,
    status: "Just In",
    title: "Nike React Infinity 3 By You",
    description:
      "The Nike React Infinity 3 By You Custom Women's Road Running Shoes feature advanced cushioning and a personalized fit for optimal running comfort. These shoes are designed to support long runs and keep you going for miles.",
    shortDescription:
      "Custom women's road running shoes with cushioning and personalized fit for long runs.",
    color: "6 Colours",
    colors: ["Pink", "Black", "Blue", "Purple", "Red", "White"],
    category: "Women's Shoes",
    inventory: 15,
    brandName: "Nike",
    tags: ["Customizable", "Running", "Cushioning"],
    sku: "NRIBYW",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 16995,
    discountedPrice: 15995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-61.png",
  },
  {
    id: 62,
    status: "Just In",
    title: "Nike Wildhorse 8",
    description:
      "The Nike Wildhorse 8 Women's Trail Running Shoes offer rugged durability and cushioning for off-road runs. With an aggressive grip and sturdy build, these shoes are designed to handle rough terrain with ease.",
    shortDescription:
      "Women's trail running shoes with rugged durability and aggressive grip for off-road runs.",
    color: "2 Colours",
    colors: ["Black", "Grey"],
    category: "Women's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Trail Running", "Durable", "Grip"],
    sku: "NWH8",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 11895,
    discountedPrice: 10995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-62.png",
  },
  {
    id: 63,
    status: "Member Access",
    title: "Air Jordan 1 Mid SE Craft",
    description:
      "The Air Jordan 1 Mid SE Craft Men's Shoes offer an elevated take on the classic Jordan 1 design with premium materials and a fresh, contemporary style. Available exclusively for members, these shoes combine iconic heritage with modern flair.",
    shortDescription:
      "Exclusive member access sneakers with premium materials and a modern twist on a classic design.",
    color: "1 Colour",
    colors: ["Brown"],
    category: "Men's Shoes",
    inventory: 6,
    brandName: "Jordan",
    tags: ["Premium", "Exclusive", "Iconic"],
    sku: "AJ1MSECR",
    returnPolicy: "No promotions available. Standard return policy of 30 days.",
    rating: 4.9,
    currentPrice: 12295,
    discountedPrice: 11995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-63.png",
  },
  {
    id: 64,
    status: "Just In",
    title: "Air Jordan XXXVII Low PF",
    description:
      "The Air Jordan XXXVII Low PF Men's Basketball Shoes offer excellent support and cushioning for on-court performance. With a low-profile design and premium materials, these shoes are built for explosive moves and maximum comfort.",
    shortDescription:
      "Low-profile basketball shoes designed for explosive moves and on-court performance.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 8,
    brandName: "Jordan",
    tags: ["Basketball", "Performance", "Cushioning"],
    sku: "AJXXXVII",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 16295,
    discountedPrice: 15995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-64.png",
  },

  {
    id: 65,
    status: "Member Access",
    title: "Zion 2 PF",
    description:
      "The Zion 2 PF Men's Basketball Shoes are designed for powerful movements on the court, offering superior grip, support, and cushioning for explosive performance.",
    shortDescription:
      "Men's basketball shoes for explosive performance with premium grip and cushioning.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Basketball", "Performance", "Grip"],
    sku: "Z2PF",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 10795,
    discountedPrice: 9995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-65.png",
  },
  {
    id: 66,
    status: "Just In",
    title: "Nike Gripknit Phantom GX Elite, Fusion FG",
    description:
      "The Nike Gripknit Phantom GX Elite Firm-Ground Football Boot is designed for football players who need an edge on the field. Featuring advanced grip and durability, this boot offers superior traction and performance on firm-ground surfaces.",
    shortDescription:
      "Firm-ground football boot with advanced grip and superior traction for performance.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Football Shoes",
    inventory: 8,
    brandName: "Nike",
    tags: ["Football", "Performance", "Grip"],
    sku: "NGPFGX",
    returnPolicy: "30 days return policy",
    rating: 4.9,
    currentPrice: 21995,
    discountedPrice: 20995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-66.png",
  },
  {
    id: 67,
    status: "Just In",
    title: "Nike Air Max 97 SE",
    description:
      "The Nike Air Max 97 SE Men's Shoes offer a classic style with advanced cushioning for comfort throughout the day. Featuring a sleek design and modern elements, these shoes are ideal for everyday wear.",
    shortDescription:
      "Classic men's shoes with advanced cushioning and sleek design for everyday wear.",
    color: "1 Colour",
    colors: ["Silver"],
    category: "Men's Shoes",
    inventory: 12,
    brandName: "Nike",
    tags: ["Classic", "Cushioning", "Comfort"],
    sku: "NAM97SE",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 17495,
    discountedPrice: 16995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-67.png",
  },
  {
    id: 68,
    status: "Just In",
    title: "Nike Pegasus Trail 4",
    description:
      "The Nike Pegasus Trail 4 Men's Trail-Running Shoes are designed to provide comfort and support on rugged terrains. With durable traction and cushioning, they are perfect for off-road running.",
    shortDescription:
      "Trail-running shoes with durable traction and cushioning for off-road running.",
    color: "1 Colour",
    colors: ["Grey"],
    category: "Men's Shoes",
    inventory: 15,
    brandName: "Nike",
    tags: ["Trail Running", "Durable", "Comfort"],
    sku: "NPT4",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 11595,
    discountedPrice: 10995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-68.png",
  },
  {
    id: 69,
    status: "Just In",
    title: "Nike Air Max 270 GO",
    description:
      "The Nike Air Max 270 GO Younger Kids' Easy On/Off Shoes are designed for little ones, offering ease of wear with a comfortable, breathable design and stylish look.",
    shortDescription:
      "Easy on/off shoes for kids with comfort, breathability, and a stylish look.",
    color: "1 Colour",
    colors: ["Red"],
    category: "Kids' Shoes",
    inventory: 20,
    brandName: "Nike",
    tags: ["Kids", "Comfortable", "Stylish"],
    sku: "NAM270GOK",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 7995,
    discountedPrice: 7495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-69.png",
  },
  {
    id: 70,
    status: "Just In",
    title: "Jordan Delta 3 Low SE",
    description:
      "The Jordan Delta 3 Low SE Women's Shoes offer a sleek design with modern comfort. These shoes provide cushioning and support, perfect for both casual wear and active use.",
    shortDescription:
      "Women's shoes with modern design, cushioning, and support for casual and active wear.",
    color: "1 Colour",
    colors: ["Pink"],
    category: "Women's Shoes",
    inventory: 10,
    brandName: "Jordan",
    tags: ["Comfortable", "Casual", "Active"],
    sku: "JDL3SE",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 12795,
    discountedPrice: 11995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-70.png",
  },
  {
    id: 71,
    status: "Just In",
    title: "Nike Zegama",
    description:
      "The Nike Zegama Men's Trail-Running Shoes are built to perform on rugged terrains. Featuring durable materials and traction, these shoes provide stability and support on challenging trails.",
    shortDescription:
      "Men's trail-running shoes with durability and traction for challenging trails.",
    color: "2 Colours",
    colors: ["Black", "Red"],
    category: "Men's Shoes",
    inventory: 9,
    brandName: "Nike",
    tags: ["Trail Running", "Durability", "Support"],
    sku: "NZEG",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 13995,
    discountedPrice: 12995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-71.png",
  },
  {
    id: 72,
    status: "Member Access",
    title: "NikeCourt Air Zoom Vapor 9.5 Tour Premium",
    description:
      "The NikeCourt Air Zoom Vapor 9.5 Tour Premium Men's Tennis Shoes offer speed, stability, and support on the court. Featuring advanced Zoom Air cushioning and a durable rubber outsole, these shoes are designed for tennis players who demand performance.",
    shortDescription:
      "Premium men's tennis shoes with advanced Zoom Air cushioning and support for the court.",
    color: "1 Colour",
    colors: ["White"],
    category: "Tennis Shoes",
    inventory: 5,
    brandName: "Nike",
    tags: ["Tennis", "Performance", "Cushioning"],
    sku: "NCAZV9",
    returnPolicy: "No promotions available. Standard return policy of 30 days.",
    rating: 4.8,
    currentPrice: 15995,
    discountedPrice: 14995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-72.png",
  },

  {
    id: 73,
    status: "Just In",
    title: "Nike Sportswear",
    description:
      "The Nike Sportswear Women's Ribbed Jersey Short Sleeve Top combines comfort with a trendy ribbed design. Ideal for casual wear, it provides a fitted look and is made of soft jersey fabric.",
    shortDescription:
      "Women's ribbed jersey short sleeve top for a comfortable and trendy look.",
    color: "2 Colours",
    colors: ["Black", "White"],
    category: "Women's Apparel",
    inventory: 15,
    brandName: "Nike",
    tags: ["Casual", "Comfort", "Fashion"],
    sku: "NSWS",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 3295,
    discountedPrice: 2995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-73.png",
  },
  {
    id: 74,
    status: "Just In",
    title: "Nike Sportswear",
    description:
      "The Nike Sportswear Women's High Waisted Ribbed Jersey Trousers offer a stylish and comfortable fit. Made from soft ribbed jersey, these trousers are perfect for casual or lounge wear.",
    shortDescription:
      "Women's high-waisted ribbed jersey trousers for comfort and style.",
    color: "1 Colour",
    colors: ["Grey"],
    category: "Women's Apparel",
    inventory: 10,
    brandName: "Nike",
    tags: ["Casual", "Comfort", "Fashion"],
    sku: "NSWTR",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 3995,
    discountedPrice: 3795,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-74.png",
  },
  {
    id: 75,
    status: "Sustainable Materials",
    title: "Nike Air",
    description:
      "The Nike Air Women's Jumpsuit is crafted with sustainable materials, offering both comfort and eco-conscious fashion. Perfect for a relaxed yet stylish look.",
    shortDescription:
      "Sustainable women's jumpsuit offering comfort and eco-conscious style.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Apparel",
    inventory: 8,
    brandName: "Nike",
    tags: ["Sustainable", "Fashion", "Comfort"],
    sku: "NAJ",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 6295,
    discountedPrice: 5995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-75.png",
  },
  {
    id: 76,
    status: "Sustainable Materials",
    title: "Nike Air",
    description:
      "The Nike Air Women's Woven Jacket combines sustainable materials with a sleek design for a versatile outer layer. Great for layering over athletic or casual outfits.",
    shortDescription:
      "Sustainable women's woven jacket for stylish layering and comfort.",
    color: "1 Colour",
    colors: ["Beige"],
    category: "Women's Outerwear",
    inventory: 6,
    brandName: "Nike",
    tags: ["Sustainable", "Fashion", "Outerwear"],
    sku: "NAWJ",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 7295,
    discountedPrice: 6995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-76.png",
  },
  {
    id: 77,
    status: "Just In",
    title: "Nike Sportswear",
    description:
      "The Nike Sportswear Older Kids' (Girls') T-Shirt is a simple, stylish, and comfortable tee. Made from soft cotton, it’s perfect for everyday wear.",
    shortDescription:
      "Soft and comfortable t-shirt for older girls, perfect for everyday wear.",
    color: "1 Colour",
    colors: ["Pink"],
    category: "Kids' Apparel",
    inventory: 18,
    brandName: "Nike",
    tags: ["Comfortable", "Casual", "Kids"],
    sku: "NSWT",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 1295,
    discountedPrice: 1195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-77.png",
  },
  {
    id: 78,
    status: "Just In",
    title: "Nike Sportswear",
    description:
      "The Nike Sportswear Women's High Waisted Ribbed Jersey Shorts offer a perfect blend of comfort and style. The ribbed design gives these shorts a fashionable touch for casual wear.",
    shortDescription:
      "High-waisted ribbed jersey shorts for women, combining comfort and style.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Apparel",
    inventory: 12,
    brandName: "Nike",
    tags: ["Casual", "Comfort", "Fashion"],
    sku: "NSWHS",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 2495,
    discountedPrice: 2295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-78.png",
  },
  {
    id: 79,
    status: "Just In",
    title: "Jordan Series",
    description:
      "The Jordan Series Women's Shoes provide a modern, sleek design with a comfortable fit. Perfect for everyday wear or casual outings, these shoes offer support and style.",
    shortDescription:
      "Sleek and comfortable women's shoes for everyday wear and casual outings.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Shoes",
    inventory: 10,
    brandName: "Jordan",
    tags: ["Casual", "Comfort", "Sleek"],
    sku: "JSW",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 7495,
    discountedPrice: 6995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-79.png",
  },
  {
    id: 80,
    status: "Just In",
    title: "Nike Brasilia JDI",
    description:
      "The Nike Brasilia JDI Kids' Mini Backpack (11L) is perfect for young adventurers. Compact and functional, it provides enough room for essentials like snacks, books, and small toys.",
    shortDescription:
      "Compact kids' mini backpack offering functionality and style for young adventurers.",
    color: "2 Colours",
    colors: ["Blue", "Pink"],
    category: "Kids' Accessories",
    inventory: 20,
    brandName: "Nike",
    tags: ["Kids", "Backpack", "Functional"],
    sku: "NBJDI",
    returnPolicy: "30 days return policy",
    rating: 4.8,
    currentPrice: 1595,
    discountedPrice: 1495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-80.png",
  },

  {
    id: 81,
    status: "Just In",
    title: "Nike Air Max Excee",
    description:
      "The Nike Air Max Excee is designed for comfort and style. With its retro-inspired look and modern comfort features, it’s a versatile shoe for any occasion.",
    shortDescription:
      "Women's Air Max shoes combining retro style and modern comfort.",
    color: "1 Colour",
    colors: ["White"],
    category: "Women's Shoes",
    inventory: 15,
    brandName: "Nike",
    tags: ["Retro", "Comfort", "Style"],
    sku: "NAEX",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 7995,
    discountedPrice: 7495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-81.png",
  },
  {
    id: 82,
    status: "Promo Exclusion",
    title: "Nike Air Force 1 Low Retro",
    description:
      "The Nike Air Force 1 Low Retro is a timeless classic with a modern twist. Made for men, these shoes offer superior comfort, style, and durability.",
    shortDescription:
      "Classic low-top men's Air Force 1 shoes with retro style.",
    color: "1 Colour",
    colors: ["White"],
    category: "Men's Shoes",
    inventory: 10,
    brandName: "Nike",
    tags: ["Classic", "Durable", "Comfort"],
    sku: "NAFLR",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 13995,
    discountedPrice: 12995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-82.png",
  },
  {
    id: 83,
    status: "Just In",
    title: "Nike Sunray Protect 2",
    description:
      "The Nike Sunray Protect 2 Baby/Toddler Sandals are perfect for little feet. These sandals provide comfort, protection, and support, making them ideal for outdoor activities.",
    shortDescription:
      "Comfortable and protective sandals for babies and toddlers.",
    color: "2 Colours",
    colors: ["Pink", "Blue"],
    category: "Baby/Toddler Footwear",
    inventory: 20,
    brandName: "Nike",
    tags: ["Toddler", "Comfort", "Outdoor"],
    sku: "NSP2",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 2495,
    discountedPrice: 2295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-83.png",
  },
  {
    id: 84,
    status: "Just In",
    title: "Nike City Rep TR",
    description:
      "The Nike City Rep TR Men's Training Shoes are designed to provide stability, support, and comfort for a variety of workouts. Ideal for cross-training, they offer durability and performance.",
    shortDescription:
      "Men's training shoes designed for stability and support during workouts.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Training Footwear",
    inventory: 18,
    brandName: "Nike",
    tags: ["Training", "Support", "Stability"],
    sku: "NCRTR",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 4995,
    discountedPrice: 4795,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-84.png",
  },
  {
    id: 85,
    status: "Just In",
    title: "Nike Dri-FIT AeroBill",
    description:
      "The Nike Dri-FIT AeroBill Women's Golf Visor offers superior moisture-wicking technology and sun protection, keeping you cool and dry on the course.",
    shortDescription:
      "Women's golf visor with moisture-wicking technology for comfort.",
    color: "2 Colours",
    colors: ["White", "Black"],
    category: "Women's Golf Accessories",
    inventory: 25,
    brandName: "Nike",
    tags: ["Golf", "Moisture-Wicking", "Sun Protection"],
    sku: "NDFA",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 1295,
    discountedPrice: 1195,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-85.png",
  },
  {
    id: 86,
    status: "Just In",
    title: "Nike SuperRep Go 3 Next Nature Flyknit",
    description:
      "The Nike SuperRep Go 3 Next Nature Flyknit Men's Training Shoes are designed for high-intensity workouts, offering flexibility, breathability, and a lightweight fit.",
    shortDescription:
      "Lightweight men's training shoes designed for high-intensity workouts.",
    color: "1 Colour",
    colors: ["Grey"],
    category: "Men's Training Footwear",
    inventory: 15,
    brandName: "Nike",
    tags: ["Training", "Lightweight", "High-Intensity"],
    sku: "NSRG3",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 8895,
    discountedPrice: 8495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-86.png",
  },
  {
    id: 87,
    status: "Just In",
    title: "Nike Dri-FIT Academy 23",
    description:
      "The Nike Dri-FIT Academy 23 Women's Football Shorts are designed for peak performance on the field. Made with breathable Dri-FIT fabric, they provide comfort and moisture control.",
    shortDescription:
      "Breathable women's football shorts with Dri-FIT technology for moisture control.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Women's Football Apparel",
    inventory: 12,
    brandName: "Nike",
    tags: ["Football", "Dri-FIT", "Performance"],
    sku: "NDFA23",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 1595,
    discountedPrice: 1495,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-87.png",
  },
  {
    id: 88,
    status: "Just In",
    title: "Nike Air Max SYSTM",
    description:
      "The Nike Air Max SYSTM Men's Shoes combine classic Air Max comfort with modern styling. These shoes are built for everyday wear, offering support and style.",
    shortDescription:
      "Modern men's Air Max shoes offering comfort and everyday wearability.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Men's Shoes",
    inventory: 14,
    brandName: "Nike",
    tags: ["Air Max", "Comfort", "Everyday"],
    sku: "NAMXS",
    returnPolicy: "30 days return policy",
    rating: 4.7,
    currentPrice: 8595,
    discountedPrice: 8295,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-88.png",
  },

  {
    id: 89,
    status: "Just In",
    title: "Nike Dri-FIT Academy",
    description:
      "The Nike Dri-FIT Academy Older Kids' Woven Football Tracksuit Bottoms provide superior comfort and breathability, keeping young athletes cool and dry during training.",
    shortDescription:
      "Breathable and comfortable woven tracksuit bottoms for older kids.",
    color: "1 Colour",
    colors: ["Black"],
    category: "Kids' Football Apparel",
    inventory: 25,
    brandName: "Nike",
    tags: ["Football", "Dri-FIT", "Kids"],
    sku: "NDFAK",
    returnPolicy: "30 days return policy",
    rating: 4.5,
    currentPrice: 2195,
    discountedPrice: 1995,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-89.png",
  },
  {
    id: 90,
    status: "Sustainable Materials",
    title: "NikeCourt Legacy",
    description:
      "The NikeCourt Legacy Men's Shoes are made with sustainable materials, combining style and eco-friendliness. Perfect for both on-court and everyday wear.",
    shortDescription:
      "Eco-friendly men's shoes designed with sustainable materials.",
    color: "2 Colours",
    colors: ["White", "Black"],
    category: "Men's Shoes",
    inventory: 18,
    brandName: "Nike",
    tags: ["Sustainable", "Eco-friendly", "Tennis"],
    sku: "NCLMS",
    returnPolicy: "30 days return policy",
    rating: 4.6,
    currentPrice: 5695,
    discountedPrice: 5395,
    imagesUrls: "https://nike-ecommerce-template-3.vercel.app/images/products/product-90.png",
  },
];
